<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dtmgimp.proto

namespace DtmGrpc\GPB\DtmGimp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>dtmgimp.DtmTransOptions</code>
 */
class DtmTransOptions extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool WaitResult = 1;</code>
     */
    protected $WaitResult = false;
    /**
     * Generated from protobuf field <code>int64 TimeoutToFail = 2;</code>
     */
    protected $TimeoutToFail = 0;
    /**
     * Generated from protobuf field <code>int64 RetryInterval = 3;</code>
     */
    protected $RetryInterval = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $WaitResult
     *     @type int|string $TimeoutToFail
     *     @type int|string $RetryInterval
     * }
     */
    public function __construct($data = NULL) {
        \DtmGrpc\GPB\GPBMetadata\Dtmgimp::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool WaitResult = 1;</code>
     * @return bool
     */
    public function getWaitResult()
    {
        return $this->WaitResult;
    }

    /**
     * Generated from protobuf field <code>bool WaitResult = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setWaitResult($var)
    {
        GPBUtil::checkBool($var);
        $this->WaitResult = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 TimeoutToFail = 2;</code>
     * @return int|string
     */
    public function getTimeoutToFail()
    {
        return $this->TimeoutToFail;
    }

    /**
     * Generated from protobuf field <code>int64 TimeoutToFail = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimeoutToFail($var)
    {
        GPBUtil::checkInt64($var);
        $this->TimeoutToFail = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 RetryInterval = 3;</code>
     * @return int|string
     */
    public function getRetryInterval()
    {
        return $this->RetryInterval;
    }

    /**
     * Generated from protobuf field <code>int64 RetryInterval = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRetryInterval($var)
    {
        GPBUtil::checkInt64($var);
        $this->RetryInterval = $var;

        return $this;
    }

}

